[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_2 = "CxjEfd1Lee8vDfZpHi4jVpVzYVGTJ4nCert3NWZM7k1u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ronaldkoh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
