[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_4 = "FUeSDCmveSq648274E3ib9sQH54Ec2Hg4xRRVRy6PFkX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ronaldkoh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
